spring.application.name=BadmintonShop
# Server Port
server.port=8080

# Database Connection (SQL Server)
# ??i c?ng 1433 và tên database t??ng ?ng
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=badminton_shop_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sa123456

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect